name: Production Deploy

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: node-hello
  ECS_CLUSTER: prod-cluster
  ECS_SERVICE: prod-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Run tests
      run: |
        npm ci
        npm test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build and push to ECR
      run: |
        # Login to ECR
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 820672722254.dkr.ecr.ap-southeast-1.amazonaws.com
        
        # Build and push with latest tag
        docker build -t 820672722254.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:latest .
        docker push 820672722254.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:latest

    - name: Deploy to ECS
      run: |
        # Force new deployment to pull latest image
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment \
          --region $AWS_REGION

    - name: Wait for deployment
      run: |
        echo "Waiting for ECS deployment to complete..."
        aws ecs wait services-stable \
          --cluster $ECS_CLUSTER \
          --services $ECS_SERVICE \
          --region $AWS_REGION
        echo "✅ Deployment completed successfully!"