name: Production Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (plan or apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd infra/prod
        terraform init

    - name: Terraform Plan
      run: |
        cd infra/prod
        terraform plan

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        cd infra/prod
        terraform apply -auto-approve